Traceback (most recent call last):
  File "c:\users\aaron\miniconda37\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\aaron\miniconda37\lib\site-packages\nbclient\client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\aaron\miniconda37\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\aaron\miniconda37\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\aaron\miniconda37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\users\aaron\miniconda37\lib\site-packages\nbclient\client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\aaron\miniconda37\lib\site-packages\nbclient\client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\aaron\miniconda37\lib\site-packages\nbclient\client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# %load E13_2_connect.py
import sqlite3                          # åŒ¯å…¥sqlite3å¥—ä»¶

conn = sqlite3.connect('singMatch.db')  # é€£ç·šè³‡æ–™åº«
conn.close()                            # é—œé–‰è³‡æ–™åº«

with sqlite3.connect('singMatch2.db') as conn: # é€£ç·šè³‡æ–™åº«  
  conn.close()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mProgrammingError[0m                          Traceback (most recent call last)
[1;32m<ipython-input-1-dbe36b7f8695>[0m in [0;36m<module>[1;34m[0m
[0;32m      6[0m [1;33m[0m[0m
[0;32m      7[0m [1;32mwith[0m [0msqlite3[0m[1;33m.[0m[0mconnect[0m[1;33m([0m[1;34m'singMatch2.db'[0m[1;33m)[0m [1;32mas[0m [0mconn[0m[1;33m:[0m [1;31m# é€£ç·šè³‡æ–™åº«[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 8[1;33m   [0mconn[0m[1;33m.[0m[0mclose[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;31mProgrammingError[0m: Cannot operate on a closed database.
ProgrammingError: Cannot operate on a closed database.

