Traceback (most recent call last):
  File "c:\users\aaron\miniconda37\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\aaron\miniconda37\lib\site-packages\nbclient\client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\aaron\miniconda37\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\aaron\miniconda37\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\aaron\miniconda37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\users\aaron\miniconda37\lib\site-packages\nbclient\client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\aaron\miniconda37\lib\site-packages\nbclient\client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\aaron\miniconda37\lib\site-packages\nbclient\client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#È°ØÁ§∫Â≠∏ÁîüÊàêÁ∏æË°®
import sqlite3
dbfile = "school.db"
conn = sqlite3.connect(dbfile)
rows = conn.execute("select * from score;")
for row in rows:
    for field in row:
        print("{}\t".format(field), end="")
    print()
conn.close()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mOperationalError[0m                          Traceback (most recent call last)
[1;32m<ipython-input-1-8d671016f12f>[0m in [0;36m<module>[1;34m[0m
[0;32m      3[0m [0mdbfile[0m [1;33m=[0m [1;34m"school.db"[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m [0mconn[0m [1;33m=[0m [0msqlite3[0m[1;33m.[0m[0mconnect[0m[1;33m([0m[0mdbfile[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 5[1;33m [0mrows[0m [1;33m=[0m [0mconn[0m[1;33m.[0m[0mexecute[0m[1;33m([0m[1;34m"select * from score;"[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      6[0m [1;32mfor[0m [0mrow[0m [1;32min[0m [0mrows[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m      7[0m     [1;32mfor[0m [0mfield[0m [1;32min[0m [0mrow[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;31mOperationalError[0m: no such table: score
OperationalError: no such table: score

